### ISSUE TITLE
KeyError: 'XDG_CURRENT_DESKTOP'

### ISSUE THREAD

**Issue by weggingt** [DozyDolphin/Worksets#7]
I believe I installed all of the dependencies and ran the pip3 installer but when I try and run the program I get this error.  

Traceback (most recent call last):
  File "/home/weggingt/.local/bin/worksets", line 7, in <module>
    from worksets.__main__ import run
  File "/home/weggingt/.local/lib/python3.5/site-packages/worksets/__main__.py", line 61, in <module>
    run()
  File "/home/weggingt/.local/lib/python3.5/site-packages/worksets/__main__.py", line 54, in run
    main = Main()
  File "/home/weggingt/.local/lib/python3.5/site-packages/worksets/main.py", line 46, in __init__
    wm = Wm(publisher)
  File "/home/weggingt/.local/lib/python3.5/site-packages/worksets/system/wm.py", line 32, in __init__
    desktop_env = os.environ['XDG_CURRENT_DESKTOP'].lower()
  File "/usr/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'XDG_CURRENT_DESKTOP'

What can I do to resolve this?

**Comment by DozyDolphin** [comment]
Hi weggingt

It's trying to determine your desktop environment. 
Which distribution and desktop environment are you using?

EDIT: Please try and run `echo $XDG_CURRENT_DESKTOP` in your terminal

**Comment by weggingt** [comment]
Oh.  Well that would explain a lot.  I'm using the latest Ubuntu "Zesty" and my desktop is OpenBox.

Doing echo $XDG_CURRENT_DESKTOP does nothing so I guess if that doesn't yield a result then your software has no idea what to do next?

**Comment by DozyDolphin** [comment]
Okay ...try `echo $DESKTOP_SESSION` and see what that nets you.

Also try `wmctrl -d` from the command line. This is the command to make wmctrl output your number of desktops. 

- If you have multiple virtual desktops enabled, but the output only shows a single desktop, I'll help you muck around a bit and see if we can it running (This is how Unity works). 
- If you have multiple virtual desktops enabled _and_ the output shows multiple desktops, then we'll have to wait until Issue #1 is fixed, since you won't have any luck getting it to work in the current state.

But of course, the application shouldn't crash on you. Thank you for notifying me about it - I'll add some checks to that part.

Let me know what you find :-)

**Comment by weggingt** [comment]
Echo $DESKTOP_SESSION does nothing.

wmctrl -d:

weggingt@Danger:~$ wmctrl -d
0  * DG: 3584x1440  VP: 0,0  WA: 0,29 3584x1411  Work
1  - DG: 3584x1440  VP: 0,0  WA: 0,29 3584x1411  Web
2  - DG: 3584x1440  VP: 0,0  WA: 0,29 3584x1411  System

But. . . not sure that gives you what you would need.  I have two monitors side by side.  The one on the left is 1024 x 768 and the one on the right is 2560 x 1440.  They both sit in "X screen 0"

![2017-07-11--1499760425_547x373_scrot](https://user-images.githubusercontent.com/8953252/28057598-b1f85740-65dd-11e7-8dde-e0995cad4466.png)

**Comment by DozyDolphin** [comment]
Weird - I've made a feature request at OpenBox to ask for them to implement XDG_CURRENT_DESKTOP or alternative ways to determine OpenBox as the DE. 
If you find a way please let me know.

**Regarding wmctrl:** It gives me exactly what I need :-)
It is reporting your virtual desktops as it should (as far as I understand). 
Unity doesn't do this, and so Worksets unfortunately _won't work_ on OpenBox since I developed it to work with Unity.

**But...** Issue #1 is adding support for Gnome-Shell, which reports virtual desktops in the same way as Openbox. So, barring any other issues specific with OpenBox, when I have that support implemented (hopefully in the following week), we could possibly get it working, if you're willing to help me test it?

It does however require a way to determine that the desktop environment is OpenBox from the command line. I'm awaiting answers from the feature/bug list on OpenBox, but it would be a great help if you could do some reasearch into how you can determine OpenBox is the DE from the commandline/terminal?

**Comment by weggingt** [comment]
wmctrl -m will report what window manager is being used.  

It reports back "Name: Openbox"  Would that do it?  It is already one of your dependencies.  

~$ wmctrl -m
Name: Openbox

**Comment by DozyDolphin** [comment]
Yes... that would do it. Thank you.

I'll get back to you when I have gnome-shell support working, and an implementation to allow it to work on OpenBox

**Comment by DozyDolphin** [comment]
Hi weggingt,

[worksets-0.2.dev0.tar.gz](https://github.com/DozyDolphin/Worksets/files/1144678/worksets-0.2.dev0.tar.gz)

this is a little quick build before I stop for today.
Gnome support is working at my end, and I should have fixed this Issue #7.
Worksets should now work on open box, but it is using the gnome implementation. 

If you're willing to try it out, please let me know your experience.

I am experiencing a problem at the moment, where, on gnome, nautilus and gnome-tweak-tool doesn't adjust sizes correctly. If you get that far, please see how that works for you (I'm running it in a vm)

You should be able to install it in [the same way as v0.1](https://github.com/DozyDolphin/Worksets/wiki/How-to-install,-run-or-uninstall-worksets) - do an uninstall first.

Good day
